### ISSUE TITLE
Configure JupyterHub to Use Custom User Image and Shared Data PVCs

### ISSUE THREAD

**Issue by jtayl222** [jtayl222/k3s-homelab#2]
**Labels:** `enhancement`, `jupyterhub`, `helm`, `storage`, `ansible` 

**Description:**

This issue tracks the configuration of our JupyterHub deployment to leverage a custom user Docker image and mount shared Persistent Volume Claims (PVCs) for data and ML artifacts. This is essential for enabling interactive data science and ML development on the platform, allowing data scientists to access pipeline-generated data and artifacts directly from their notebooks.

**Current State:**

  * K3s cluster deployed via Ansible.
  * JupyterHub is deployed in the `jupyterhub` namespace via Ansible/Helm, using default or existing configurations.
  * A custom JupyterHub user image (`jtayl22/financial-predictor-jupyter:latest`) has been built and pushed to Docker Hub, containing project-specific Python dependencies (e.g., `pytorch`, `yfinance`, `mlflow`).
  * Shared PVCs (`shared-data-pvc` and `shared-artifacts-pvc`) exist in the `financial-mlops-pytorch` namespace, used by Argo Workflows for pipeline data and artifacts.

**Problem to Solve:**
Currently, JupyterHub user pods:

1.  Do not use the `jtayl22/financial-predictor-jupyter:latest` image, meaning they lack the necessary Python libraries for financial ML development.
2.  Do not have the `shared-data-pvc` and `shared-artifacts-pvc` mounted, preventing interactive access to processed data and MLflow artifacts.
3.  Are not configured to point to the MLflow Tracking Server, hindering experiment tracking from notebooks.

**Proposed Solution / Acceptance Criteria:**

Modify the JupyterHub Helm chart values (`values.yaml`) and apply these changes via Ansible.

**Specific Changes Required:**

1.  **Update `singleuser.image`:**

      * Configure JupyterHub to use the custom user image:
        ```yaml
        singleuser:
          image:
            name: jtayl22/financial-predictor-jupyter
            tag: latest
        ```

2.  **Mount Shared PVCs:**

      * Add `extraVolumes` and `extraVolumeMounts` to expose the shared data and artifacts PVCs to user pods. The mount paths should be consistent with the paths used by Argo Workflows (e.g., `/mnt/shared-data`, `/mnt/shared-artifacts`).
        ```yaml
        singleuser:
          # ... (other singleuser settings) ...
          extraVolumes:
            - name: shared-ml-data-pvc
              persistentVolumeClaim:
                claimName: shared-data-pvc # Ensure this PVC exists in 'financial-mlops-pytorch' NS
            - name: shared-ml-artifacts-pvc
              persistentVolumeClaim:
                claimName: shared-artifacts-pvc # Ensure this PVC exists in 'financial-mlops-pytorch' NS
          extraVolumeMounts:
            - name: shared-ml-data-pvc
              mountPath: /mnt/shared-data
            - name: shared-ml-artifacts-pvc
              mountPath: /mnt/shared-artifacts
        ```
      * **Note:** The `claimName`s (`shared-data-pvc`, `shared-artifacts-pvc`) must refer to PVCs that are in the *same namespace as the JupyterHub user pods*. If your user pods default to a different namespace (e.g., `jupyterhub-users` or `default`), and your data PVCs are in `financial-mlops-pytorch`, you might need to adjust the PVC strategy (e.g., ensure PVCs are accessible across namespaces if your StorageClass supports it, or create dedicated PVCs in `jupyterhub` namespace and sync data). **For now, assume user pods and data PVCs are in the same namespace OR the StorageClass allows cross-namespace access (common for shared storage).** *If this becomes an issue, we'll open a follow-up issue on cross-namespace storage.*

3.  **Configure MLflow Tracking URI:**

      * Set an environment variable in the user pods to point to the MLflow Tracking Server:
        ```yaml
        singleuser:
          # ... (other singleuser settings) ...
          extraEnv:
            MLFLOW_TRACKING_URI: "http://mlflow-service.mlflow.svc.cluster.local:5000"
        ```
      * Verify the actual service name and namespace for your MLflow deployment (`mlflow-service.mlflow.svc.cluster.local` is a common default).

**Implementation Steps (for the assignee):**

1.  Locate the JupyterHub `values.yaml` file used by the Ansible playbook at `infrastructure/cluster/roles/platform/jupyterhub/tasks/main.yml`.
2.  Modify this `values.yaml` with the changes described above.
3.  Test the Ansible playbook to ensure the changes are applied to the k3s cluster without errors.
4.  Verify that new JupyterHub user pods:
      * Pull the correct `jtayl22/financial-predictor-jupyter:latest` image.
      * Have `/mnt/shared-data` and `/mnt/shared-artifacts` mounted with the expected contents.
      * Can successfully log experiments to the MLflow Tracking Server from a notebook.

-----
